<?php
/**
 * ValidateMenuItemsRequestItemsInnerTest
 *
 * PHP version 8.1
 *
 * @package  MenuClientApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Menu Service API
 *
 * Restaurant menu management service
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MenuClientApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ValidateMenuItemsRequestItemsInnerTest Class Doc Comment
 *
 * @description ValidateMenuItemsRequestItemsInner
 * @package     MenuClientApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ValidateMenuItemsRequestItemsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ValidateMenuItemsRequestItemsInner"
     */
    public function testValidateMenuItemsRequestItemsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
