<?php
/**
 * DefaultApi
 * PHP version 8.1
 *
 * @package  BillingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billing Service API
 *
 * Restaurant payment processing and refunds
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BillingApi\BillingClient;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BillingApi\ApiException;
use BillingApi\Configuration;
use BillingApi\HeaderSelector;
use BillingApi\FormDataProcessor;
use BillingApi\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @package  BillingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'capturePayment' => [
            'application/json',
        ],
        'createPaymentIntent' => [
            'application/json',
        ],
        'createRefund' => [
            'application/json',
        ],
        'getBillingHealth' => [
            'application/json',
        ],
        'getPaymentIntent' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation capturePayment
     *
     * Capture payment
     *
     * @param  string $payment_id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['capturePayment'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function capturePayment(
        string $payment_id,
        string $contentType = self::contentTypes['capturePayment'][0]
    ): void
    {
        $this->capturePaymentWithHttpInfo($payment_id, $contentType);
    }

    /**
     * Operation capturePaymentWithHttpInfo
     *
     * Capture payment
     *
     * @param  string $payment_id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['capturePayment'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function capturePaymentWithHttpInfo(
        string $payment_id,
        string $contentType = self::contentTypes['capturePayment'][0]
    ): array
    {
        $request = $this->capturePaymentRequest($payment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'capturePayment',
                'url.template' => '/v1/billing/payments/{paymentId}/capture'
            ];
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation capturePaymentAsync
     *
     * Capture payment
     *
     * @param  string $payment_id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['capturePayment'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function capturePaymentAsync(
        string $payment_id,
        string $contentType = self::contentTypes['capturePayment'][0]
    ): PromiseInterface
    {
        return $this->capturePaymentAsyncWithHttpInfo($payment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation capturePaymentAsyncWithHttpInfo
     *
     * Capture payment
     *
     * @param  string $payment_id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['capturePayment'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function capturePaymentAsyncWithHttpInfo(
        string $payment_id,
        string $contentType = self::contentTypes['capturePayment'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->capturePaymentRequest($payment_id, $contentType);
        $options = $this->createHttpClientOption();
        $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'capturePayment',
                'url.template' => '/v1/billing/payments/{paymentId}/capture'
            ];
        return $this->client
            ->sendAsync($request, $options)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'capturePayment'
     *
     * @param  string $payment_id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['capturePayment'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function capturePaymentRequest(
        string $payment_id,
        string $contentType = self::contentTypes['capturePayment'][0]
    ): Request
    {

        // verify the required parameter 'payment_id' is set
        if ($payment_id === null || (is_array($payment_id) && count($payment_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $payment_id when calling capturePayment'
            );
        }


        $resourcePath = '/v1/billing/payments/{paymentId}/capture';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($payment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'paymentId' . '}',
                ObjectSerializer::toPathValue($payment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createPaymentIntent
     *
     * Create payment intent
     *
     * @param  \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request create_payment_intent_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPaymentIntent'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \BillingApi\Model\CreatePaymentIntent201Response
     */
    public function createPaymentIntent(
        \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request,
        string $contentType = self::contentTypes['createPaymentIntent'][0]
    ): \BillingApi\Model\CreatePaymentIntent201Response
    {
        list($response) = $this->createPaymentIntentWithHttpInfo($create_payment_intent_request, $contentType);
        return $response;
    }

    /**
     * Operation createPaymentIntentWithHttpInfo
     *
     * Create payment intent
     *
     * @param  \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPaymentIntent'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \BillingApi\Model\CreatePaymentIntent201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createPaymentIntentWithHttpInfo(
        \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request,
        string $contentType = self::contentTypes['createPaymentIntent'][0]
    ): array
    {
        $request = $this->createPaymentIntentRequest($create_payment_intent_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'createPaymentIntent',
                'url.template' => '/v1/billing/payment-intents'
            ];
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\BillingApi\Model\CreatePaymentIntent201Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BillingApi\Model\CreatePaymentIntent201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BillingApi\Model\CreatePaymentIntent201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation createPaymentIntentAsync
     *
     * Create payment intent
     *
     * @param  \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPaymentIntent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createPaymentIntentAsync(
        \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request,
        string $contentType = self::contentTypes['createPaymentIntent'][0]
    ): PromiseInterface
    {
        return $this->createPaymentIntentAsyncWithHttpInfo($create_payment_intent_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createPaymentIntentAsyncWithHttpInfo
     *
     * Create payment intent
     *
     * @param  \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPaymentIntent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createPaymentIntentAsyncWithHttpInfo(
        \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request,
        string $contentType = self::contentTypes['createPaymentIntent'][0]
    ): PromiseInterface
    {
        $returnType = '\BillingApi\Model\CreatePaymentIntent201Response';
        $request = $this->createPaymentIntentRequest($create_payment_intent_request, $contentType);
        $options = $this->createHttpClientOption();
        $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'createPaymentIntent',
                'url.template' => '/v1/billing/payment-intents'
            ];
        return $this->client
            ->sendAsync($request, $options)
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createPaymentIntent'
     *
     * @param  \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPaymentIntent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createPaymentIntentRequest(
        \BillingApi\Model\CreatePaymentIntentRequest $create_payment_intent_request,
        string $contentType = self::contentTypes['createPaymentIntent'][0]
    ): Request
    {

        // verify the required parameter 'create_payment_intent_request' is set
        if ($create_payment_intent_request === null || (is_array($create_payment_intent_request) && count($create_payment_intent_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $create_payment_intent_request when calling createPaymentIntent'
            );
        }


        $resourcePath = '/v1/billing/payment-intents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_payment_intent_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_payment_intent_request));
            } else {
                $httpBody = $create_payment_intent_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createRefund
     *
     * Create refund
     *
     * @param  \BillingApi\Model\CreateRefundRequest $create_refund_request create_refund_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRefund'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function createRefund(
        \BillingApi\Model\CreateRefundRequest $create_refund_request,
        string $contentType = self::contentTypes['createRefund'][0]
    ): void
    {
        $this->createRefundWithHttpInfo($create_refund_request, $contentType);
    }

    /**
     * Operation createRefundWithHttpInfo
     *
     * Create refund
     *
     * @param  \BillingApi\Model\CreateRefundRequest $create_refund_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRefund'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createRefundWithHttpInfo(
        \BillingApi\Model\CreateRefundRequest $create_refund_request,
        string $contentType = self::contentTypes['createRefund'][0]
    ): array
    {
        $request = $this->createRefundRequest($create_refund_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'createRefund',
                'url.template' => '/v1/billing/refunds'
            ];
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation createRefundAsync
     *
     * Create refund
     *
     * @param  \BillingApi\Model\CreateRefundRequest $create_refund_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRefund'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createRefundAsync(
        \BillingApi\Model\CreateRefundRequest $create_refund_request,
        string $contentType = self::contentTypes['createRefund'][0]
    ): PromiseInterface
    {
        return $this->createRefundAsyncWithHttpInfo($create_refund_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createRefundAsyncWithHttpInfo
     *
     * Create refund
     *
     * @param  \BillingApi\Model\CreateRefundRequest $create_refund_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRefund'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createRefundAsyncWithHttpInfo(
        \BillingApi\Model\CreateRefundRequest $create_refund_request,
        string $contentType = self::contentTypes['createRefund'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->createRefundRequest($create_refund_request, $contentType);
        $options = $this->createHttpClientOption();
        $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'createRefund',
                'url.template' => '/v1/billing/refunds'
            ];
        return $this->client
            ->sendAsync($request, $options)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createRefund'
     *
     * @param  \BillingApi\Model\CreateRefundRequest $create_refund_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRefund'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createRefundRequest(
        \BillingApi\Model\CreateRefundRequest $create_refund_request,
        string $contentType = self::contentTypes['createRefund'][0]
    ): Request
    {

        // verify the required parameter 'create_refund_request' is set
        if ($create_refund_request === null || (is_array($create_refund_request) && count($create_refund_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $create_refund_request when calling createRefund'
            );
        }


        $resourcePath = '/v1/billing/refunds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_refund_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_refund_request));
            } else {
                $httpBody = $create_refund_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBillingHealth
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBillingHealth'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \BillingApi\Model\GetBillingHealth200Response
     */
    public function getBillingHealth(
        string $contentType = self::contentTypes['getBillingHealth'][0]
    ): \BillingApi\Model\GetBillingHealth200Response
    {
        list($response) = $this->getBillingHealthWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getBillingHealthWithHttpInfo
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBillingHealth'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \BillingApi\Model\GetBillingHealth200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBillingHealthWithHttpInfo(
        string $contentType = self::contentTypes['getBillingHealth'][0]
    ): array
    {
        $request = $this->getBillingHealthRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'getBillingHealth',
                'url.template' => '/v1/billing/health'
            ];
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BillingApi\Model\GetBillingHealth200Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BillingApi\Model\GetBillingHealth200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BillingApi\Model\GetBillingHealth200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getBillingHealthAsync
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBillingHealth'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getBillingHealthAsync(
        string $contentType = self::contentTypes['getBillingHealth'][0]
    ): PromiseInterface
    {
        return $this->getBillingHealthAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBillingHealthAsyncWithHttpInfo
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBillingHealth'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getBillingHealthAsyncWithHttpInfo(
        string $contentType = self::contentTypes['getBillingHealth'][0]
    ): PromiseInterface
    {
        $returnType = '\BillingApi\Model\GetBillingHealth200Response';
        $request = $this->getBillingHealthRequest($contentType);
        $options = $this->createHttpClientOption();
        $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'getBillingHealth',
                'url.template' => '/v1/billing/health'
            ];
        return $this->client
            ->sendAsync($request, $options)
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBillingHealth'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBillingHealth'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBillingHealthRequest(
        string $contentType = self::contentTypes['getBillingHealth'][0]
    ): Request
    {


        $resourcePath = '/v1/billing/health';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPaymentIntent
     *
     * Get payment intent
     *
     * @param  string $id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentIntent'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \BillingApi\Model\PaymentIntent|\BillingApi\Model\GetPaymentIntent404Response
     */
    public function getPaymentIntent(
        string $id,
        string $contentType = self::contentTypes['getPaymentIntent'][0]
    ): \BillingApi\Model\PaymentIntent|\BillingApi\Model\GetPaymentIntent404Response
    {
        list($response) = $this->getPaymentIntentWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getPaymentIntentWithHttpInfo
     *
     * Get payment intent
     *
     * @param  string $id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentIntent'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \BillingApi\Model\PaymentIntent|\BillingApi\Model\GetPaymentIntent404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentIntentWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['getPaymentIntent'][0]
    ): array
    {
        $request = $this->getPaymentIntentRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'getPaymentIntent',
                'url.template' => '/v1/billing/payment-intents/{id}'
            ];
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BillingApi\Model\PaymentIntent',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\BillingApi\Model\GetPaymentIntent404Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BillingApi\Model\PaymentIntent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BillingApi\Model\PaymentIntent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BillingApi\Model\GetPaymentIntent404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getPaymentIntentAsync
     *
     * Get payment intent
     *
     * @param  string $id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentIntent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getPaymentIntentAsync(
        string $id,
        string $contentType = self::contentTypes['getPaymentIntent'][0]
    ): PromiseInterface
    {
        return $this->getPaymentIntentAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentIntentAsyncWithHttpInfo
     *
     * Get payment intent
     *
     * @param  string $id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentIntent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getPaymentIntentAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['getPaymentIntent'][0]
    ): PromiseInterface
    {
        $returnType = '\BillingApi\Model\PaymentIntent';
        $request = $this->getPaymentIntentRequest($id, $contentType);
        $options = $this->createHttpClientOption();
        $options['otel_attributes'] = [
                'peer.service' => 'BillingApi',
                'peer.operation' => 'getPaymentIntent',
                'url.template' => '/v1/billing/payment-intents/{id}'
            ];
        return $this->client
            ->sendAsync($request, $options)
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPaymentIntent'
     *
     * @param  string $id Payment intent ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentIntent'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaymentIntentRequest(
        string $id,
        string $contentType = self::contentTypes['getPaymentIntent'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling getPaymentIntent'
            );
        }


        $resourcePath = '/v1/billing/payment-intents/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
