<?php
/**
 * DefaultApi
 * PHP version 8.1
 *
 * @package  MenuApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Menu Service API
 *
 * Restaurant menu management service
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MenuApi\MenuClient;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use MenuApi\ApiException;
use MenuApi\Configuration;
use MenuApi\HeaderSelector;
use MenuApi\FormDataProcessor;
use MenuApi\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @package  MenuApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createMenuItem' => [
            'application/json',
        ],
        'getMenuHealth' => [
            'application/json',
        ],
        'getMenuItem' => [
            'application/json',
        ],
        'listMenuItems' => [
            'application/json',
        ],
        'updateMenuItem' => [
            'application/json',
        ],
        'updateMenuItemAvailability' => [
            'application/json',
        ],
        'validateMenuItems' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation createMenuItem
     *
     * Create a menu item
     *
     * @param  \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request create_menu_item_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMenuItem'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \MenuApi\Model\MenuItem
     */
    public function createMenuItem(
        \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request,
        string $contentType = self::contentTypes['createMenuItem'][0]
    ): \MenuApi\Model\MenuItem
    {
        list($response) = $this->createMenuItemWithHttpInfo($create_menu_item_request, $contentType);
        return $response;
    }

    /**
     * Operation createMenuItemWithHttpInfo
     *
     * Create a menu item
     *
     * @param  \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMenuItem'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \MenuApi\Model\MenuItem, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMenuItemWithHttpInfo(
        \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request,
        string $contentType = self::contentTypes['createMenuItem'][0]
    ): array
    {
        $request = $this->createMenuItemRequest($create_menu_item_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\MenuApi\Model\MenuItem',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MenuApi\Model\MenuItem',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MenuApi\Model\MenuItem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation createMenuItemAsync
     *
     * Create a menu item
     *
     * @param  \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createMenuItemAsync(
        \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request,
        string $contentType = self::contentTypes['createMenuItem'][0]
    ): PromiseInterface
    {
        return $this->createMenuItemAsyncWithHttpInfo($create_menu_item_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMenuItemAsyncWithHttpInfo
     *
     * Create a menu item
     *
     * @param  \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createMenuItemAsyncWithHttpInfo(
        \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request,
        string $contentType = self::contentTypes['createMenuItem'][0]
    ): PromiseInterface
    {
        $returnType = '\MenuApi\Model\MenuItem';
        $request = $this->createMenuItemRequest($create_menu_item_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMenuItem'
     *
     * @param  \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createMenuItemRequest(
        \MenuApi\Model\CreateMenuItemRequest $create_menu_item_request,
        string $contentType = self::contentTypes['createMenuItem'][0]
    ): Request
    {

        // verify the required parameter 'create_menu_item_request' is set
        if ($create_menu_item_request === null || (is_array($create_menu_item_request) && count($create_menu_item_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $create_menu_item_request when calling createMenuItem'
            );
        }


        $resourcePath = '/v1/menu/items';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_menu_item_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_menu_item_request));
            } else {
                $httpBody = $create_menu_item_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMenuHealth
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuHealth'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \MenuApi\Model\GetMenuHealth200Response
     */
    public function getMenuHealth(
        string $contentType = self::contentTypes['getMenuHealth'][0]
    ): \MenuApi\Model\GetMenuHealth200Response
    {
        list($response) = $this->getMenuHealthWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getMenuHealthWithHttpInfo
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuHealth'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \MenuApi\Model\GetMenuHealth200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMenuHealthWithHttpInfo(
        string $contentType = self::contentTypes['getMenuHealth'][0]
    ): array
    {
        $request = $this->getMenuHealthRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MenuApi\Model\GetMenuHealth200Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MenuApi\Model\GetMenuHealth200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MenuApi\Model\GetMenuHealth200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getMenuHealthAsync
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuHealth'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getMenuHealthAsync(
        string $contentType = self::contentTypes['getMenuHealth'][0]
    ): PromiseInterface
    {
        return $this->getMenuHealthAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMenuHealthAsyncWithHttpInfo
     *
     * Health check
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuHealth'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getMenuHealthAsyncWithHttpInfo(
        string $contentType = self::contentTypes['getMenuHealth'][0]
    ): PromiseInterface
    {
        $returnType = '\MenuApi\Model\GetMenuHealth200Response';
        $request = $this->getMenuHealthRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMenuHealth'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuHealth'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMenuHealthRequest(
        string $contentType = self::contentTypes['getMenuHealth'][0]
    ): Request
    {


        $resourcePath = '/v1/menu/health';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMenuItem
     *
     * Get a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuItem'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \MenuApi\Model\MenuItem|\MenuApi\Model\GetMenuItem404Response
     */
    public function getMenuItem(
        string $id,
        string $contentType = self::contentTypes['getMenuItem'][0]
    ): \MenuApi\Model\MenuItem|\MenuApi\Model\GetMenuItem404Response
    {
        list($response) = $this->getMenuItemWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getMenuItemWithHttpInfo
     *
     * Get a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuItem'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \MenuApi\Model\MenuItem|\MenuApi\Model\GetMenuItem404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMenuItemWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['getMenuItem'][0]
    ): array
    {
        $request = $this->getMenuItemRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MenuApi\Model\MenuItem',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\MenuApi\Model\GetMenuItem404Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MenuApi\Model\MenuItem',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MenuApi\Model\MenuItem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MenuApi\Model\GetMenuItem404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation getMenuItemAsync
     *
     * Get a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getMenuItemAsync(
        string $id,
        string $contentType = self::contentTypes['getMenuItem'][0]
    ): PromiseInterface
    {
        return $this->getMenuItemAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMenuItemAsyncWithHttpInfo
     *
     * Get a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getMenuItemAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['getMenuItem'][0]
    ): PromiseInterface
    {
        $returnType = '\MenuApi\Model\MenuItem';
        $request = $this->getMenuItemRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMenuItem'
     *
     * @param  string $id Menu item ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMenuItemRequest(
        string $id,
        string $contentType = self::contentTypes['getMenuItem'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling getMenuItem'
            );
        }


        $resourcePath = '/v1/menu/items/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listMenuItems
     *
     * List all menu items
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMenuItems'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \MenuApi\Model\ListMenuItems200Response
     */
    public function listMenuItems(
        string $contentType = self::contentTypes['listMenuItems'][0]
    ): \MenuApi\Model\ListMenuItems200Response
    {
        list($response) = $this->listMenuItemsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation listMenuItemsWithHttpInfo
     *
     * List all menu items
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMenuItems'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \MenuApi\Model\ListMenuItems200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listMenuItemsWithHttpInfo(
        string $contentType = self::contentTypes['listMenuItems'][0]
    ): array
    {
        $request = $this->listMenuItemsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MenuApi\Model\ListMenuItems200Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MenuApi\Model\ListMenuItems200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MenuApi\Model\ListMenuItems200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation listMenuItemsAsync
     *
     * List all menu items
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMenuItems'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listMenuItemsAsync(
        string $contentType = self::contentTypes['listMenuItems'][0]
    ): PromiseInterface
    {
        return $this->listMenuItemsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listMenuItemsAsyncWithHttpInfo
     *
     * List all menu items
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMenuItems'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listMenuItemsAsyncWithHttpInfo(
        string $contentType = self::contentTypes['listMenuItems'][0]
    ): PromiseInterface
    {
        $returnType = '\MenuApi\Model\ListMenuItems200Response';
        $request = $this->listMenuItemsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listMenuItems'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMenuItems'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listMenuItemsRequest(
        string $contentType = self::contentTypes['listMenuItems'][0]
    ): Request
    {


        $resourcePath = '/v1/menu/items';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateMenuItem
     *
     * Update a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemRequest|null $update_menu_item_request update_menu_item_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItem'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function updateMenuItem(
        string $id,
        ?\MenuApi\Model\UpdateMenuItemRequest $update_menu_item_request = null,
        string $contentType = self::contentTypes['updateMenuItem'][0]
    ): void
    {
        $this->updateMenuItemWithHttpInfo($id, $update_menu_item_request, $contentType);
    }

    /**
     * Operation updateMenuItemWithHttpInfo
     *
     * Update a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemRequest|null $update_menu_item_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItem'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateMenuItemWithHttpInfo(
        string $id,
        ?\MenuApi\Model\UpdateMenuItemRequest $update_menu_item_request = null,
        string $contentType = self::contentTypes['updateMenuItem'][0]
    ): array
    {
        $request = $this->updateMenuItemRequest($id, $update_menu_item_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation updateMenuItemAsync
     *
     * Update a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemRequest|null $update_menu_item_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function updateMenuItemAsync(
        string $id,
        ?\MenuApi\Model\UpdateMenuItemRequest $update_menu_item_request = null,
        string $contentType = self::contentTypes['updateMenuItem'][0]
    ): PromiseInterface
    {
        return $this->updateMenuItemAsyncWithHttpInfo($id, $update_menu_item_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateMenuItemAsyncWithHttpInfo
     *
     * Update a menu item
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemRequest|null $update_menu_item_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function updateMenuItemAsyncWithHttpInfo(
        string $id,
        ?\MenuApi\Model\UpdateMenuItemRequest $update_menu_item_request = null,
        string $contentType = self::contentTypes['updateMenuItem'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->updateMenuItemRequest($id, $update_menu_item_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMenuItem'
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemRequest|null $update_menu_item_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItem'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateMenuItemRequest(
        string $id,
        ?\MenuApi\Model\UpdateMenuItemRequest $update_menu_item_request = null,
        string $contentType = self::contentTypes['updateMenuItem'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling updateMenuItem'
            );
        }



        $resourcePath = '/v1/menu/items/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_menu_item_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_menu_item_request));
            } else {
                $httpBody = $update_menu_item_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateMenuItemAvailability
     *
     * Update item availability
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request update_menu_item_availability_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItemAvailability'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function updateMenuItemAvailability(
        string $id,
        \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request,
        string $contentType = self::contentTypes['updateMenuItemAvailability'][0]
    ): void
    {
        $this->updateMenuItemAvailabilityWithHttpInfo($id, $update_menu_item_availability_request, $contentType);
    }

    /**
     * Operation updateMenuItemAvailabilityWithHttpInfo
     *
     * Update item availability
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItemAvailability'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateMenuItemAvailabilityWithHttpInfo(
        string $id,
        \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request,
        string $contentType = self::contentTypes['updateMenuItemAvailability'][0]
    ): array
    {
        $request = $this->updateMenuItemAvailabilityRequest($id, $update_menu_item_availability_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation updateMenuItemAvailabilityAsync
     *
     * Update item availability
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItemAvailability'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function updateMenuItemAvailabilityAsync(
        string $id,
        \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request,
        string $contentType = self::contentTypes['updateMenuItemAvailability'][0]
    ): PromiseInterface
    {
        return $this->updateMenuItemAvailabilityAsyncWithHttpInfo($id, $update_menu_item_availability_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateMenuItemAvailabilityAsyncWithHttpInfo
     *
     * Update item availability
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItemAvailability'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function updateMenuItemAvailabilityAsyncWithHttpInfo(
        string $id,
        \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request,
        string $contentType = self::contentTypes['updateMenuItemAvailability'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->updateMenuItemAvailabilityRequest($id, $update_menu_item_availability_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMenuItemAvailability'
     *
     * @param  string $id Menu item ID (required)
     * @param  \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMenuItemAvailability'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateMenuItemAvailabilityRequest(
        string $id,
        \MenuApi\Model\UpdateMenuItemAvailabilityRequest $update_menu_item_availability_request,
        string $contentType = self::contentTypes['updateMenuItemAvailability'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling updateMenuItemAvailability'
            );
        }

        // verify the required parameter 'update_menu_item_availability_request' is set
        if ($update_menu_item_availability_request === null || (is_array($update_menu_item_availability_request) && count($update_menu_item_availability_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $update_menu_item_availability_request when calling updateMenuItemAvailability'
            );
        }


        $resourcePath = '/v1/menu/items/{id}/availability';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_menu_item_availability_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_menu_item_availability_request));
            } else {
                $httpBody = $update_menu_item_availability_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation validateMenuItems
     *
     * Validate menu items
     *
     * @param  \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request validate_menu_items_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateMenuItems'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \MenuApi\Model\ValidateMenuItems200Response
     */
    public function validateMenuItems(
        \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request,
        string $contentType = self::contentTypes['validateMenuItems'][0]
    ): \MenuApi\Model\ValidateMenuItems200Response
    {
        list($response) = $this->validateMenuItemsWithHttpInfo($validate_menu_items_request, $contentType);
        return $response;
    }

    /**
     * Operation validateMenuItemsWithHttpInfo
     *
     * Validate menu items
     *
     * @param  \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateMenuItems'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \MenuApi\Model\ValidateMenuItems200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateMenuItemsWithHttpInfo(
        \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request,
        string $contentType = self::contentTypes['validateMenuItems'][0]
    ): array
    {
        $request = $this->validateMenuItemsRequest($validate_menu_items_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MenuApi\Model\ValidateMenuItems200Response',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MenuApi\Model\ValidateMenuItems200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MenuApi\Model\ValidateMenuItems200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation validateMenuItemsAsync
     *
     * Validate menu items
     *
     * @param  \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateMenuItems'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function validateMenuItemsAsync(
        \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request,
        string $contentType = self::contentTypes['validateMenuItems'][0]
    ): PromiseInterface
    {
        return $this->validateMenuItemsAsyncWithHttpInfo($validate_menu_items_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateMenuItemsAsyncWithHttpInfo
     *
     * Validate menu items
     *
     * @param  \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateMenuItems'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function validateMenuItemsAsyncWithHttpInfo(
        \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request,
        string $contentType = self::contentTypes['validateMenuItems'][0]
    ): PromiseInterface
    {
        $returnType = '\MenuApi\Model\ValidateMenuItems200Response';
        $request = $this->validateMenuItemsRequest($validate_menu_items_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateMenuItems'
     *
     * @param  \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateMenuItems'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function validateMenuItemsRequest(
        \MenuApi\Model\ValidateMenuItemsRequest $validate_menu_items_request,
        string $contentType = self::contentTypes['validateMenuItems'][0]
    ): Request
    {

        // verify the required parameter 'validate_menu_items_request' is set
        if ($validate_menu_items_request === null || (is_array($validate_menu_items_request) && count($validate_menu_items_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $validate_menu_items_request when calling validateMenuItems'
            );
        }


        $resourcePath = '/v1/menu/validation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($validate_menu_items_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($validate_menu_items_request));
            } else {
                $httpBody = $validate_menu_items_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
