<?php
/**
 * DefaultApiTest
 * PHP version 8.1
 *
 * @package  BillingClientApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billing Service API
 *
 * Restaurant payment processing and refunds
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BillingClientApiClient\Test\Api;

use BillingClientApiClient\Configuration;
use BillingClientApiClient\ApiException;
use BillingClientApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package  BillingClientApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for capturePayment
     *
     * Capture payment.
     *
     */
    public function testCapturePayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPaymentIntent
     *
     * Create payment intent.
     *
     */
    public function testCreatePaymentIntent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRefund
     *
     * Create refund.
     *
     */
    public function testCreateRefund()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingHealth
     *
     * Health check.
     *
     */
    public function testGetBillingHealth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentIntent
     *
     * Get payment intent.
     *
     */
    public function testGetPaymentIntent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
