<?php
/**
 * DefaultApiTest
 * PHP version 8.1
 *
 * @package  OrdersClientApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orders Service API
 *
 * Restaurant order management and workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OrdersClientApiClient\Test\Api;

use OrdersClientApiClient\Configuration;
use OrdersClientApiClient\ApiException;
use OrdersClientApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package  OrdersClientApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelOrder
     *
     * Cancel an order.
     *
     */
    public function testCancelOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrder
     *
     * Create an order.
     *
     */
    public function testCreateOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrder
     *
     * Get an order.
     *
     */
    public function testGetOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrdersHealth
     *
     * Health check.
     *
     */
    public function testGetOrdersHealth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for orderPaymentCaptured
     *
     * Payment captured event.
     *
     */
    public function testOrderPaymentCaptured()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for orderRefunded
     *
     * Refunded event.
     *
     */
    public function testOrderRefunded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
