<?php
/**
 * ReconcileInventoryRequestTest
 *
 * PHP version 8.1
 *
 * @package  InventoryClientApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory Service API
 *
 * Restaurant inventory and stock management
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace InventoryClientApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReconcileInventoryRequestTest Class Doc Comment
 *
 * @description ReconcileInventoryRequest
 * @package     InventoryClientApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReconcileInventoryRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReconcileInventoryRequest"
     */
    public function testReconcileInventoryRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "available"
     */
    public function testPropertyAvailable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ingredients"
     */
    public function testPropertyIngredients()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
